ARG version
FROM almalinux:${version}
ARG course="DevOps with AWS" \
    Duration="120hrs"
ENV course="DevOps with AWS" \
    Duration="120hrs"
RUN echo "Course: $course, Duration: $Duration"
CMD ["sleep", "100"]